import Head from "next/head"
import Link from "next/link"

export default function Home() {
  return (
    <div className="flex flex-col items-center pt-10 gap-4">
      <Head>
        <title>Foodlert | To power the better back house</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>Welcome To Foodlert</main>

      <span>Landing Page is in progress</span>

      <div>
        <Link href="/auth/login">
          <a className="underline text-blue-800">Login</a>
        </Link>
      </div>
    </div>
  )
}
